apiVersion: apps/v1
kind: Deployment 
metadata:
  name: shopping-kart
spec:
  selector:
    matchLabels:
      app: shopping
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
        - name: shopping
          image: rachit01/shopping:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: shopping
spec:
  selector:
    app: shopping
  ports:
    - protocol: "TCP"
      port: 8070 # The port that the service is running on in the cluster
      targetPort: 8070 # The port exposed by the service
  type: LoadBalancer # type of the service.
